Repository benceBalazs/labyriX, pull requests merged in 2021-06, with the labels that each got.

#73 Implementation Board Update
  core/src/com/labyrix/game/Models/Board.java
Labels: enhancement

#74 Counting field method
  core/src/com/labyrix/game/Models/Player.java
  core/src/com/labyrix/game/Screens/HUD.java
Labels: enhancement

#77 Feature/implementation trap defuse4
  android/assets/cage.png
  core/src/com/labyrix/game/Defusions/MovementDefuse.java
  core/src/com/labyrix/game/Models/Image.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement

#78 Fix Zombie Trap Accelerometer values when phone not horitontal
  core/src/com/labyrix/game/Defusions/MovementDefuse.java
Labels: enhancement

#79 implementation HUD
  .idea/misc.xml
  core/src/com/labyrix/game/Models/HudButton.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/Screens/HUD.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement

#81 Implementation lobby logic
  core/src/com/labyrix/game/LabyrixMain.java
  core/src/com/labyrix/game/Models/NetworkPlayer.java
  core/src/com/labyrix/game/Models/Player.java
  core/src/com/labyrix/game/Network/ClientNetworkConfig.java
  core/src/com/labyrix/game/Network/ClientNetworkHandler.java
  core/src/com/labyrix/game/Network/ClientRequestListener.java
  core/src/com/labyrix/game/NetworkModels/BeginGameRequest.java
  core/src/com/labyrix/game/NetworkModels/BeginGameResponse.java
  core/src/com/labyrix/game/NetworkModels/CharacterColorRequest.java
  core/src/com/labyrix/game/NetworkModels/CharacterColorResponse.java
  core/src/com/labyrix/game/NetworkModels/LobbyCreateRequest.java
  core/src/com/labyrix/game/NetworkModels/LobbyCreateResponse.java
  core/src/com/labyrix/game/NetworkModels/LobbyJoinRequest.java
  core/src/com/labyrix/game/NetworkModels/LobbyJoinResponse.java
  core/src/com/labyrix/game/NetworkModels/LobbyLeaveResponse.java
  core/src/com/labyrix/game/NetworkModels/PlayerInstanceRequest.java
  core/src/com/labyrix/game/NetworkModels/PlayerInstanceResponse.java
  core/src/com/labyrix/game/NetworkModels/PlayerWinIdRequest.java
  core/src/com/labyrix/game/NetworkModels/PlayerWinIdResponse.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/Screens/JoinScreen.java
  core/src/com/labyrix/game/Screens/LobbyScreen.java
  server/build/jacoco/test.exec
  server/build/libs/server-1.0.jar
  server/build/reports/tests/test/css/base-style.css
  server/build/reports/tests/test/css/style.css
  server/build/reports/tests/test/index.html
  server/build/reports/tests/test/js/report.js
  server/build/test-results/test/binary/output.bin
  server/build/test-results/test/binary/output.bin.idx
  server/build/test-results/test/binary/results.bin
  server/build/tmp/compileJava/source-classes-mapping.txt
  server/build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/META-INF/MANIFEST.MF
  server/build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/META-INF/maven/org.jacoco/org.jacoco.agent/pom.properties
  server/build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/META-INF/maven/org.jacoco/org.jacoco.agent/pom.xml
  server/build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/about.html
  server/build/tmp/expandedArchives/org.jacoco.agent-0.8.5.jar_6a2df60c47de373ea127d14406367999/jacocoagent.jar
  server/build/tmp/jar/MANIFEST.MF
  server/src/main/java/com/labyrix/server/Lobby.java
  server/src/main/java/com/labyrix/server/LobbyHandler.java
  server/src/main/java/com/labyrix/server/Main.java
  server/src/main/java/com/labyrix/server/ServerNetworkConfig.java
  server/src/main/java/com/labyrix/server/ServerRequestListener.java
Labels: enhancement

#82 Board update change path
  core/src/com/labyrix/game/Models/Board.java
Labels: enhancement

#88 implementation hud2
  .idea/misc.xml
  build.gradle
  core/src/com/labyrix/game/Models/HudButton.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/Screens/HUD.java
  core/src/com/labyrix/game/TurnLogic.java
  core/src/test/TestArrowActor.java
  core/src/test/TestArrowActors.java
  core/src/test/TestClientNetworkConfig.java
  core/src/test/TestClientNetworkHandler.java
  core/src/test/TestClientRequestListener.java
  core/src/test/TestGameScreen.java
  core/src/test/TestImage.java
  core/src/test/TestJoinCreateScreen.java
  core/src/test/TestLabyrixMain.java
  core/src/test/TestLobbyScreen.java
  core/src/test/TestNonPathField.java
  core/src/test/TestPlayer.java
  core/src/test/TestStartScreen.java
  core/src/test/TestTrapDefuseMethod.java
  core/src/test/TestTrapEventName.java
  core/src/test/TestTurnLogic.java
  core/src/test/TestTurnValue.java
  settings.gradle
  tests/build.gradle
  tests/build/tmp/compileTestJava/source-classes-mapping.txt
  tests/src/de/tomgrill/gdxtesting/GdxTestRunner.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/AssetExistsExampleTest.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/CustomTestSuit.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/SuitRunner.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestBoard.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestPathField.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestTrap.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestTrapEvent.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestTurnLogic.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/UnitTestExample.java
Labels: enhancement

#89 Feature/refactor trap defusion
  android/assets/fail.png
  android/assets/success.png
  core/src/com/labyrix/game/Defusions/BombDefuse.java
  core/src/com/labyrix/game/ENUMS/TrapDefuseMethod.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement

#90 Feature/implementation uncover
  core/src/com/labyrix/game/Models/NetworkPlayer.java
  core/src/com/labyrix/game/Models/Uncover.java
  core/src/com/labyrix/game/Models/UncoverRender.java
  core/src/com/labyrix/game/Network/ClientNetworkHandler.java
  core/src/com/labyrix/game/Network/ClientRequestListener.java
  core/src/com/labyrix/game/NetworkModels/UncoverRequest.java
  core/src/com/labyrix/game/NetworkModels/UncoverResponse.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/TurnLogic.java
  server/build/libs/server-1.0.jar
  server/src/main/java/com/labyrix/server/Main.java
  server/src/main/java/com/labyrix/server/ServerRequestListener.java
  sonar-project.properties
Labels: enhancement

#92 implementation tests and inserting javadocs for hud
  core/src/com/labyrix/game/Models/Trap.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/Screens/HUD.java
  sonar-project.properties
  tests/build/tmp/compileTestJava/source-classes-mapping.txt
  tests/src/de/tomgrill/gdxtesting/labyrixTests/CustomTestSuit.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestTrap.java
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestTrapEvent.java
Labels: Tester, documentation, enhancement

#93 Test implementation Counting field Methode
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/PathField.java
  core/src/com/labyrix/game/Models/Player.java
  tests/build/tmp/compileTestJava/source-classes-mapping.txt
  tests/src/de/tomgrill/gdxtesting/labyrixTests/TestPlayer.java
Labels: DokumentatorIn, Tester
