Repository benceBalazs/labyriX, pull requests merged in 2021-05, with the labels that each got.

#38 implemented Screens
  android/assets/Create.jpg
  android/assets/Hintergrundbild.png
  android/assets/Join.jpg
  android/assets/Playnow.jpg
  android/assets/Start.jpg
  android/assets/bildApp.png
  android/assets/schriftApp.jpg
  core/src/com/labyrix/game/gameScreen.java
  core/src/com/labyrix/game/joinCreateScreen.java
  core/src/com/labyrix/game/labyrixMain.java
  core/src/com/labyrix/game/lobbyScreen.java
  core/src/com/labyrix/game/startScreen.java
Labels: enhancement

#43 Implementation Trap-Activation
  android/src/com/labyrix/game/tests/SimpleUnitTests.java
  core/src/com/labyrix/game/Trap.java
Labels: enhancement

#45 Feature/implementation movement, path selection indicators
  android/assets/bodenLabyrixSnow.png
  android/assets/bodenLabyrixZiel.png
  android/assets/bodenlabyrixdarkv2.png
  android/assets/bodenlabyrixv2.png
  android/assets/img_0116.png
  android/assets/kreisIndicator.png
  android/assets/pfeilHinten.png
  android/assets/pfeilLinks.png
  android/assets/pfeilOben.png
  android/assets/pfeilRechts.png
  android/res/drawable/bodenlabyrixdarkv2.png
  android/res/drawable/bodenlabyrixv2.png
  android/res/drawable/img_0116.png
  core/src/com/labyrix/game/Board.java
  core/src/com/labyrix/game/Field.java
  core/src/com/labyrix/game/Image.java
  core/src/com/labyrix/game/NonPathField.java
  core/src/com/labyrix/game/PathField.java
  core/src/com/labyrix/game/Player.java
  core/src/com/labyrix/game/labyrixMain.java
Labels: enhancement

#48 Small changes to Pathfield
  core/src/com/labyrix/game/PathField.java
Labels: enhancement

#49 Feature/implementation basic turn logic
  android/assets/pfeilHinten.png
  android/assets/pfeilLinks.png
  android/assets/pfeilOben.png
  android/assets/pfeilRechts.png
  core/src/com/labyrix/game/ArrowActor.java
  core/src/com/labyrix/game/ArrowActors.java
  core/src/com/labyrix/game/Board.java
  core/src/com/labyrix/game/Player.java
  core/src/com/labyrix/game/TurnLogic.java
  core/src/com/labyrix/game/TurnValue.java
  core/src/com/labyrix/game/labyrixMain.java
Labels: enhancement

#50 Feature/implementation of path selection
  android/assets/hiddenFeld.png
  android/assets/pfeilHinten.png
  android/assets/pfeilLinks.png
  android/assets/pfeilOben.png
  android/assets/pfeilRechts.png
  core/src/com/labyrix/game/ArrowActor.java
  core/src/com/labyrix/game/ArrowActors.java
  core/src/com/labyrix/game/Board.java
  core/src/com/labyrix/game/Player.java
  core/src/com/labyrix/game/TurnLogic.java
  core/src/com/labyrix/game/TurnValue.java
  core/src/com/labyrix/game/labyrixMain.java
Labels: enhancement

#54 Feature/implementation turn logic continuation
  Logik Zug.png
  android/assets/arrowNewDown.png
  android/assets/arrowNewLeft.png
  android/assets/arrowNewRight.png
  android/assets/arrowNewUp.png
  android/assets/checkTrap.png
  android/assets/move.png
  android/assets/rollDice.png
  android/assets/selectPath.png
  android/assets/trapActive.png
  core/src/com/labyrix/game/ArrowActor.java
  core/src/com/labyrix/game/Board.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement

#56 Refactoring class name and restructure resources
  android/src/com/labyrix/game/AndroidLauncher.java
  android/src/com/labyrix/game/tests/SimpleUnitTests.java
  core/src/com/labyrix/game/Defusions/BombDefuse.java
  core/src/com/labyrix/game/Defusions/MovementDefuse.java
  core/src/com/labyrix/game/ENUMS/TrapDefuseMethod.java
  core/src/com/labyrix/game/ENUMS/TrapEventName.java
  core/src/com/labyrix/game/ENUMS/TurnValue.java
  core/src/com/labyrix/game/LabyrixMain.java
  core/src/com/labyrix/game/Models/ArrowActor.java
  core/src/com/labyrix/game/Models/ArrowActors.java
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/Field.java
  core/src/com/labyrix/game/Models/Image.java
  core/src/com/labyrix/game/Models/NonPathField.java
  core/src/com/labyrix/game/Models/PathField.java
  core/src/com/labyrix/game/Models/Player.java
  core/src/com/labyrix/game/Models/Trap.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/Network/ClientNetworkConfig.java
  core/src/com/labyrix/game/Network/ClientNetworkHandler.java
  core/src/com/labyrix/game/Network/ClientRequestListener.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/Screens/JoinScreen.java
  core/src/com/labyrix/game/Screens/LoadingScreen.java
  core/src/com/labyrix/game/Screens/LobbyScreen.java
  core/src/com/labyrix/game/Screens/SplashScreen.java
  core/src/com/labyrix/game/Screens/TitleScreen.java
  core/src/com/labyrix/game/TurnLogic.java
  core/src/com/labyrix/game/gameScreen.java
Labels: enhancement

#60 Refactoring all screens
  android/AndroidManifest.xml
  android/assets/background.png
  android/assets/bodenLabyrixv3.png
  android/assets/fonts/specialElite.ttf
  android/assets/lobby.png
  android/assets/logo.png
  android/assets/logoTitle.png
  android/assets/ui/uiskin.atlas
  android/assets/ui/uiskin.png
  android/assets/ui/uiskins.json
  android/src/com/labyrix/game/AndroidLauncher.java
  build.gradle
  core/src/com/labyrix/game/LabyrixMain.java
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/TextFieldFilter.java
  core/src/com/labyrix/game/Network/ClientNetworkHandler.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/Screens/JoinScreen.java
  core/src/com/labyrix/game/Screens/LoadingScreen.java
  core/src/com/labyrix/game/Screens/LobbyScreen.java
  core/src/com/labyrix/game/Screens/SplashScreen.java
  core/src/com/labyrix/game/Screens/TitleScreen.java
Labels: enhancement

#61 fix test paths
  build.gradle
  core/src/test/TestTrap.java
  core/src/test/TestTrapEvent.java
  sonar-project.properties
Labels: enhancement

#62 Implementation of Turn Logic 2
  android/assets/bomb.png
  android/assets/door.png
  android/assets/quicksand.png
  android/assets/zombie.png
  core/src/com/labyrix/game/ENUMS/TrapEventName.java
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/PathField.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/TurnLogic.java
  core/src/test/TestTrapEvent.java
Labels: enhancement

#64 Refactoring Models, turn logic, tests
  android/assets/serverstuff.png
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/PathField.java
  core/src/com/labyrix/game/TurnLogic.java
  core/src/test/TestBoard.java
  core/src/test/TestPathField.java
Labels: enhancement

#65 Bugfix in Turnlogic, ArrowActor and ArrowActors for Pathselection
  core/src/com/labyrix/game/ENUMS/TurnValue.java
  core/src/com/labyrix/game/Models/ArrowActor.java
  core/src/com/labyrix/game/Models/ArrowActors.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: bug

#67 Implementaion of dynamic path creation algorithm plus bugfix
  android/assets/bodenLabyrixZiel2.png
  core/src/com/labyrix/game/ENUMS/TurnValue.java
  core/src/com/labyrix/game/Models/ArrowActor.java
  core/src/com/labyrix/game/Models/ArrowActors.java
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/Field.java
  core/src/com/labyrix/game/Models/NonPathField.java
  core/src/com/labyrix/game/Models/PathField.java
  core/src/com/labyrix/game/Screens/TitleScreen.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement

#68 Feature/implementation trap defuse2
  core/src/com/labyrix/game/Defusions/BombDefuse.java
  core/src/com/labyrix/game/Defusions/BombRender.java
  core/src/com/labyrix/game/Defusions/MovementDefuse.java
  core/src/com/labyrix/game/Models/ArrowActors.java
  core/src/com/labyrix/game/Models/TrapEvent.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement

#70 Implementation HUD
  build.gradle
  core/src/com/labyrix/game/LabyrixMain.java
  core/src/com/labyrix/game/Models/Board.java
  core/src/com/labyrix/game/Models/Player.java
  core/src/com/labyrix/game/Screens/GameScreen.java
  core/src/com/labyrix/game/Screens/HUD.java
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement, high

#71 implementation Turn Logic, Dice Roll, Bugfix
  android/assets/diceFive.png
  android/assets/diceFour.png
  android/assets/diceOne.png
  android/assets/diceSix.png
  android/assets/diceThree.png
  android/assets/diceTwo.png
  core/src/com/labyrix/game/TurnLogic.java
Labels: enhancement
